const CARDS = {
  SET_USER_AUTH: 'CARDS_SET_USER_AUTH',
  SET_GUEST_AUTH: 'CARDS_SET_GUEST_AUTH',
};

const AUTH = {
  SIGN_UP: 'AUTH_SIGN_UP',
  SIGN_UP_SUCCESS: 'AUTH_SIGN_UP_SUCCESS',
  SIGN_UP_FAIL: 'AUTH_SIGN_UP_FAIL',
  LOG_IN: 'AUTH_LOG_IN',
  LOG_IN_SUCCESS: 'AUTH_LOG_IN_SUCCESS',
  LOG_IN_FAIL: 'AUTH_LOG_IN_FAIL',
};

export { CARDS, AUTH };
