const CARDS = {
  SET_USER_AUTH: 'CARDS_SET_USER_AUTH',
  SET_GUEST_AUTH: 'CARDS_SET_GUEST_AUTH',
};

const AUTH = {
  SIGN_UP: 'AUTH_SIGN_UP',
  SIGN_UP_SUCCESS: 'AUTH_SIGN_UP_SUCCESS',
  SIGN_UP_FAIL: 'AUTH_SIGN_UP_FAIL',
  LOG_IN: 'AUTH_LOG_IN',
  LOG_IN_SUCCESS: 'AUTH_LOG_IN_SUCCESS',
  LOG_IN_FAIL: 'AUTH_LOG_IN_FAIL',
  GUEST_LOG_IN: 'AUTH_GUEST_LOG_IN',
};

const MESSAGES = {
  ADD_MESSAGE: 'MESSAGES_ADD_MESSAGE',
  ADD_MESSAGE_SUCCESS: 'MESSAGES_ADD_MESSAGE_SUCCESS',
  ADD_MESSAGE_FAIL: 'MESSAGES_ADD_MESSAGE_FAIL',
  SET_MESSAGES: 'MESSAGES_SET_MESSAGES',
};

const ROOMS = {
  SET_ROOMS: 'ROOMS_SET_ROOMS',
  ADD_ROOM: 'ROOMS_ADD_ROOM',
  ADD_ROOM_SUCCESS: 'ROOMS_ADD_ROOM_SUCCESS',
  ADD_ROOM_FAIL: 'ROOMS_ADD_ROOM_FAIL',
  DELETE_ROOM: 'ROOMS_DELETE_ROOM',
  DELETE_ROOM_SUCCESS: 'ROOMS_DELETE_ROOM_SUCCESS',
  DELETE_ROOM_FAIL: 'ROOMS_DELETE_ROOM_FAIL',
};

export { CARDS, AUTH, MESSAGES, ROOMS };
